### ISSUE TITLE
Edge Scroll Issues

### ISSUE THREAD

**Issue by Zinovy** [IroncladGames/SinsOfADarkAge#1003]
GameID: 495641

Apparently some others occasionally had this issue. I was able to edge scroll up and one side (I forget which) but not down (and the other side).

Going in video settings, changing to another screen mode, then back to Virtual Fullscreen and clicking Apply fixed it.

**Comment by jseward** [comment]
do you have any steps to reliably recreate it?

**Comment by Zinovy** [comment]
No, it only happened in that game, an not since.

**Comment by jseward** [comment]
Should be fixed as of patch > 45188
