### ISSUE TITLE
asserts while spamming skills in team fight

### ISSUE THREAD

**Issue by Tugimus** [IroncladGames/SinsOfADarkAge#193]
Assert @ C:\Iron\Trunk\Code\Core/Math/Point.h(185)

IsGridCoordValid(gridSize, coord)

Assert @ C:\Iron\Trunk\Code\Game/Terrain/TerrainSurface.cpp(303)

IsHeightCoordValid(heightCoord)

**Comment by uncannymanny** [comment]
Probably fixed. If it happens again, I will re-open.
