### ISSUE TITLE
34589 Golem Portrait Slot Position Moves

### ISSUE THREAD

**Issue by uncannymanny** [IroncladGames/SinsOfADarkAge#206]
This is minor, but it did catch my eye.

Make a game.

Go south team.

Choose an enemy bot/golem and put him in the bottom-most (fifth) slot.

Should look like this:

![2014-02-23_00008](https://f.cloud.github.com/assets/6155683/2241517/e2396036-9cd5-11e3-8b06-c96c25e8ebc6.jpg)

Start game.

Enemy golem will move up a slot to the fourth slot.

![2014-02-23_00009](https://f.cloud.github.com/assets/6155683/2241520/0977b756-9cd6-11e3-8082-d399d8212193.jpg)

Happens for friendly and packs of golems too. Like if you fill 3,4, and 5, they will move up to 2,3,4 when you hit Start Game.

I hope this makes sense.

Moves them up in this screen too (ignore the not responding, I did it via Snipping Tool because I had limited time to take a SS during loading):

![capture sodada](https://f.cloud.github.com/assets/6155683/2241528/7a99652e-9cd6-11e3-860f-5d4d6a22aa42.PNG)

**Comment by writor** [comment]
Fixed! Golems now move to the top of the list.
