### ISSUE TITLE
35012 Quickplay Lobby Names in Chat

### ISSUE THREAD

**Issue by uncannymanny** [IroncladGames/SinsOfADarkAge#233]
Sometimes Quickplay's lobby will show a player on the enemy team joining in the chat:

![2014-03-10_00016](https://f.cloud.github.com/assets/6155683/2381050/c5bfcd2a-a8b8-11e3-81e4-506cb7fa6242.jpg)

Here you can see Tug joined (south side,) but VasFURY is shown joining as well, but he is North side.

**Comment by jseward** [comment]
Fixed as of 42744
