### ISSUE TITLE
General Chat Mini Portraits Show Up as ?s

### ISSUE THREAD

**Issue by uncannymanny** [IroncladGames/SinsOfADarkAge#278]
Here user Kortirion has a ? icon:

![2014-03-16_00009](https://f.cloud.github.com/assets/6155683/2431904/e9bdc6d8-ad49-11e3-9a92-86cf0d1c3ca9.jpg)

When I click on his profile though:

![2014-03-16_00013](https://f.cloud.github.com/assets/6155683/2431908/fbfa9a24-ad49-11e3-9913-96f653e8e2a3.jpg)

**Comment by jseward** [comment]
Fixed as of 42644

**Comment by writor** [comment]
Still seems to be an issue, unfortunately.

![screenshot-000](https://cloud.githubusercontent.com/assets/6934405/6155987/07e8352a-b1eb-11e4-804a-0b3371ebb367.jpg)

Screenshot taken on the live servers, 12:39 PM PST, February 11th.
