### ISSUE TITLE
Xeros' Q doesn't teleport

### ISSUE THREAD

**Issue by scarletblade** [IroncladGames/SinsOfADarkAge#291]
If the ability (slayer's mark/ Q) is pressed in rapid succession after targeting a target, there is a high chance the second part of the ability (teleport) will not function since the projectile is still flying without marking the target yet.
This is more likely to happen if the target is moving away from xeros since it will increase the flight time of the projectile.
Tested in bot's match on heroes.

**Comment by writor** [comment]
Closing this one, but linking to #597. Thanks everyone!
