### ISSUE TITLE
FPS drops, 200ms+ ping

### ISSUE THREAD

**Issue by dv0l0ty** [IroncladGames/SinsOfADarkAge#299]
I played like 5 games, but every time, at random moments i am getting massive FPS drops. From 60 it jumps to 1 and freezes for 1-2 seconds. Also, the ping is jumping too. The lowest one so far i was able to get was 200ms, which is also horrible. Sometimes it jumps to 300-380ms. Its unplayable like this.

**Comment by uncannymanny** [comment]
Probably fixed. If it happens again, I will re-open.
