### ISSUE TITLE
Need Fonts to Chat With other Countries

### ISSUE THREAD

**Issue by uncannymanny** [IroncladGames/SinsOfADarkAge#302]
Wolter Sullivan:

"You need to add fonts to chat to other countries""

**Comment by writor** [comment]
As of patch 42555, there is a new font which should support many more character sets/languages! Cyrllic and many other alphabets are included, with more to come. Please get in touch with Wolter and tell him to submit a new issue if his language of choice still isn't covered.

http://steamcommunity.com/app/251970/discussions/7/606068060813577596/
