### ISSUE TITLE
Cannot Scroll In-Match Chat Without Mousewheel

### ISSUE THREAD

**Issue by uncannymanny** [IroncladGames/SinsOfADarkAge#314]
ChrisHateZ:
"Can you scroll up the chat without mouse?
My mouse scroll doesn't work (not game's fault) so I can't use it to scroll the chat. I couldn't find any key in the options menu for that. I tried page down/up and that doesn't work either. "

"So I need an alternative option to scroll the chat so I can read up things that I miss when not paying attention. Obviously the in-game chat doesn't have the scroll bar =( "

**Comment by writor** [comment]
I don't know when it went in, but scrollwheel now works with the in-game chat! From what I can tell, chat has to be active, and you have to move the mouse over it. Thanks for the suggestion Manny/Chris.
