### ISSUE TITLE
Cyrillic characters problem, Steam profile name

### ISSUE THREAD

**Issue by rottingcorpse** [IroncladGames/SinsOfADarkAge#318]
Steam profile name (which is in russian), displayed as bunch of ? signs in game's main menu.

**Comment by writor** [comment]
At long last! As of patch 42555, there is a new font which should support many more character sets/languages! Cyrllic and many other alphabets are included, with more to come. Thanks for the report!

http://steamcommunity.com/app/251970/discussions/7/606068060813577596/
