### ISSUE TITLE
Bug: Target Outlines/Prioritization

### ISSUE THREAD

**Issue by Zinovy** [IroncladGames/SinsOfADarkAge#322]
Some abilities that can only be used on certain targets (enemies, allies, etc) are often blocked by cursor prioritizing. 

For example a few minutes ago I was Ermuk and we had a Skalla. She was fighting Rachna when I arrived and tried to heal her. I could not, no matter where I clicked, because my cursor was always considered to be targeting Rachna. Skalla could have moved but she didn't know - I just want to emphasize this was not a quick few clicks, it was an entire fight where I tried targeting between legs, etc.

So I guess the suggestion is to make the targeting cursor prioritize nearby valid targets (for the current ability) to the clicking point within a (very) small distance.

**Comment by writor** [comment]
The latest patch added "Unit Targeting Modes." This could also help generally (though not with the specific example above.) 

http://steamcommunity.com/app/251970/discussions/7/606068060813577596/

In the future, you might also be able to heal her by clicking on her portrait. (A little known cheat!)
