### ISSUE TITLE
Bulwark not breaking CC

### ISSUE THREAD

**Issue by Tugimus** [IroncladGames/SinsOfADarkAge#347]
Zinovy from Steam Forums

Flung: CC?

Abilities that fling you, such as Ermuk's flying kick, Grugg's Hamfist, or Slag's Big One, don't allow glyphs while you are disabled meaning you cannot use the CC removal Bulwark. I have yet to test items. But I wanted to ask if this is intentional before bug reporting.

**Comment by uncannymanny** [comment]
Probably fixed. If it happens again, I will re-open.
