### ISSUE TITLE
Browsing Gear Highlight Error

### ISSUE THREAD

**Issue by Tugimus** [IroncladGames/SinsOfADarkAge#361]
When you select a piece of gear in the Edit Hero pane it becomes highlighted.  If you scroll so the highlighted one is out of view, the highlighted area overlaps the border.
![2014-03-29_00005](https://cloud.githubusercontent.com/assets/6116828/2558167/874d156a-b737-11e3-8034-c57f34593aa2.jpg)
![2014-03-29_00004](https://cloud.githubusercontent.com/assets/6116828/2558168/88663c7e-b737-11e3-9d03-2fa7ca5da9ef.jpg)

**Comment by uncannymanny** [comment]
Seems that the highlight and Okay are gone.

Now it updates the Gear upon clicking.

Closing.
