### ISSUE TITLE
Graphics: Major Slowdown FPS

### ISSUE THREAD

**Issue by Zinovy** [IroncladGames/SinsOfADarkAge#372]
Momentary but significant drops in FPS that make the game appear frozen still sometimes occur. A player mentioned having this each time our Dekain used abilities. In that same game I hadn't had any during the match until chasing that player who was having them - when they appeared for me out of brush my screen hiccuped.

One time also, I got this from an ability being used which I had already seen used in that match. Whereas it never caused an FPS drop when the enemy used it normally, this time the enemy (Slag: Big One) used his ability from brush, and the explosion caused a few seconds of visual jarring.

**Comment by fyst** [comment]
Numerous performance optimizations and added graphic settings should render this obsolete.
