### ISSUE TITLE
Camera Movement - Champion won't walk

### ISSUE THREAD

**Issue by Hardy22** [IroncladGames/SinsOfADarkAge#380]
Hey, I want to report a really annoying bug...if that is one..I'm not quite sure. 

Normally a lot of players use the edge of the monitor to scroll over the map. Since I'm playing DOTA 2 I'm using the WASD Camera Movement...it's easier for me to play.

When I set the keybinding "WASD" to the camera movement for scroll up, down, left ..etc.. I started to play some games. 

The major problem about this is.. when you right click (Hero) to any point of the map and then use WASD for the Camera to scroll around...suddenly the hero stops walking. Sometimes it happens when the hero walks into the screen and you're using up/down. (He stops walking) .. 

After I lost a looooot of games, while I used this "nice feature" :D cause the Hero stops, while I was gotten chased... I tried using the "edge of scroll" so...without any WASD camera movements and the walk of the hero / champion works fine.

Would be really awesome if this actually would work with WASD too.

best regards

Thomas

**Comment by writor** [comment]
This has been fixed, you're now alerted when multi-binding keys. Thanks Hardy22!
