### ISSUE TITLE
Crashing all night

### ISSUE THREAD

**Issue by BlueTycronus** [IroncladGames/SinsOfADarkAge#386]
As Lithoron, running back to defend base.  DC'd coming out of South East Jungle at southern team's 2nd tower.
![crash 1](https://cloud.githubusercontent.com/assets/7183383/2621854/4f6aa3de-bc72-11e3-858b-4e7f281be469.png)

**Comment by uncannymanny** [comment]
Probably fixed. If it happens again, I will re-open.
