### ISSUE TITLE
Bug: characters stop processing actions and commands.

### ISSUE THREAD

**Issue by likneon** [IroncladGames/SinsOfADarkAge#391]
I play with myself keybuildings but not with the default. I set up "camera moving" for buttons WASD and when I moving the camera to look ahead of my character it stops processing all actions and commands like moving, attack and etc.

P.S. I've liked this game very much and I'll appretiate if you fix that bug. Characters in the game are fantastic and exellent done.

**Comment by writor** [comment]
The interface now warns about duplicates. Thanks for the report!
