### ISSUE TITLE
Pre-game chat screen was from old match

### ISSUE THREAD

**Issue by Tugimus** [IroncladGames/SinsOfADarkAge#396]
When I queued up and started the hero select, my team's chat window was actually the chat from the previous game I closed, and I could not type in it.

![2014-04-06_00003](https://cloud.githubusercontent.com/assets/6116828/2626119/fa3ff458-bdbc-11e3-8c2f-0a2f58ebc08e.jpg)

Game ID 27034

let me know if you want the log file

**Comment by uncannymanny** [comment]
Probably fixed. If it happens again, I will re-open.
