### ISSUE TITLE
"Search for Match" sometimes doesn't do anything

### ISSUE THREAD

**Issue by shenox** [IroncladGames/SinsOfADarkAge#488]
So I've saw this happening quite often now. I try to queue up, the button "Search for Match" grays out but the timer for estimated wait time and actual wait time won't appear, giving me no option to cancel the buggy queue other than relogging completely.

I can't even chat in any chatroom as it seems.

**Comment by uncannymanny** [comment]
Probably fixed. If it happens again, I will re-open.
