### ISSUE TITLE
Glacial Scepter Passive Question

### ISSUE THREAD

**Issue by uncannymanny** [IroncladGames/SinsOfADarkAge#493]
![scepter](https://cloud.githubusercontent.com/assets/6155683/2974741/f830daae-db8c-11e3-8d76-60435f104365.png)

Should Glacial Scepter's text here have the word "Passive" (or Unique Passive) in front of it?

Former tooltip:

https://cloud.githubusercontent.com/assets/6155683/2559686/f4b7eaae-b786-11e3-8f8e-d02446311247.jpg

**Comment by writor** [comment]
It definitely should list Passive or Unique Passive...the question is which? Since it used to be Unique, I'm going to assume it still is and @Bulletsponge can correct if needed. Rev 42746. Thanks Manny!
