### ISSUE TITLE
(Gameplay/Item) Blade of the Magi

### ISSUE THREAD

**Issue by Zinovy** [IroncladGames/SinsOfADarkAge#494]
The passive temporary attack speed boost triggers when de-activating toggle abilities. Only confirmed with Beroth's Vine Aura thing.

**Comment by writor** [comment]
It looks like this is still an issue as of internal build 41704. I tested with Beroth's W, Flailing Vines. Deactivating reset the Blade of the Magi buff timer.

**Comment by Bulletsponge** [comment]
Fixed in build 41760
