### ISSUE TITLE
AccountIsNotInChannel Steam Error

### ISSUE THREAD

**Issue by uncannymanny** [IroncladGames/SinsOfADarkAge#525]
After match 46286, I noticed my F12 wasn't working.

I queued up, and realized that General Chat had people in it but no one was talking.

I entered lobby chat and voiced my concerns to teammates and then got this:

![2014-06-01_00006](https://cloud.githubusercontent.com/assets/6155683/3141436/067f8a7c-e97c-11e3-9584-444d04fae985.jpg)

Eventually I was able to use F12 again to get the pic above.

Logged out and back in and it fixed itself.

**Comment by jseward** [comment]
fixed as of 42131 thanks to manny's help

**Comment by uncannymanny** [comment]
Everything cool I do is accidental.
