### ISSUE TITLE
non stacking items

### ISSUE THREAD

**Issue by bonesax** [IroncladGames/SinsOfADarkAge#593]
I'm looking at a recipe (mind you I am a few peieces short) but even if I had them, I would not be able to craft them since the items aren't stacking. So it's saying that I don't have 1 of something since they aren't stacked. 

I didn't screen shot every item, I figure you can get the gist of it through this picture.

![1](https://cloud.githubusercontent.com/assets/8140465/3560438/222a4b98-096d-11e4-8e39-fffc1772905d.png)

**Comment by uncannymanny** [comment]
Hope this is fixed. If not I will re-open.
