### ISSUE TITLE
Surrender box scaling, or displaying improperly

### ISSUE THREAD

**Issue by Tugimus** [IroncladGames/SinsOfADarkAge#601]
The surrender box seems to be displaying improperly.  Potentially from HUD scaling?

![2014-07-17_00001](https://cloud.githubusercontent.com/assets/6116828/3617341/8adda364-0ddd-11e4-84b1-a123d0d49951.jpg)
![2014-07-15_00002](https://cloud.githubusercontent.com/assets/6116828/3617342/8adf24fa-0ddd-11e4-83bd-9d3acf5f71a5.jpg)

**Comment by uncannymanny** [comment]
Hope this is fixed. If not I will re-open.
