### ISSUE TITLE
Vexie Skin Name Mouseover

### ISSUE THREAD

**Issue by DaManDaMythDaLegnd** [IroncladGames/SinsOfADarkAge#607]
When placing mouse over the Vexie default skin the skin name pop up truncates to two lines. Like this:

Vexi
e

**Comment by writor** [comment]
At some point, this was fixed!

![skin name](https://cloud.githubusercontent.com/assets/6934405/5593083/f163015c-91a8-11e4-97c5-ae56038978a0.jpg)

Thanks @DaManDaMythDaLegnd!
