### ISSUE TITLE
Heartsap Amulet PH Buff Icon Indicator

### ISSUE THREAD

**Issue by uncannymanny** [IroncladGames/SinsOfADarkAge#618]
When Heartsap Amulet procs, its tooltip reads as "PH-Heartsap Amulet."

![heartsap](https://cloud.githubusercontent.com/assets/6155683/3933318/da760eba-247c-11e4-8ebb-2431f578438c.png)

**Comment by writor** [comment]
Thanks Veric King! This has been fixed. The changes should show up in the next patch. Stay tuned for possible new art as well!
