### ISSUE TITLE
Vallamere Heroic Stand Question

### ISSUE THREAD

**Issue by uncannymanny** [IroncladGames/SinsOfADarkAge#619]
![heroic stand](https://cloud.githubusercontent.com/assets/6155683/3933334/2a378b72-247d-11e4-863a-87597a5e0448.png)

Heroic Stand refers to a percentage in its tooltip, yet the percentage isn't listed.

Should the percentage be listed there?

**Comment by writor** [comment]
Great suggestion Manny. A stat line listing Percentage Health should appear in the next patch. It will appear in all internal builds, Rev 42745 forward. Thanks!
