### ISSUE TITLE
Game history tab

### ISSUE THREAD

**Issue by Oblivionn** [IroncladGames/SinsOfADarkAge#626]
When victory is selected, losses are shown,
![2014-08-21_00001](https://cloud.githubusercontent.com/assets/7982804/3994254/a4856a72-2917-11e4-9141-c4f74680a0c9.jpg)
and vice versa.
![2014-08-21_00002](https://cloud.githubusercontent.com/assets/7982804/3994255/a48cbdea-2917-11e4-9182-645e9691c8d9.jpg)

**Comment by writor** [comment]
Thanks for the reports, @Oblivionn and @ProfessorJinx! It looks like one of the ninjas on staff silently took care of this!
