### ISSUE TITLE
AccountIsNotInChannel

### ISSUE THREAD

**Issue by ProfessorJinx** [IroncladGames/SinsOfADarkAge#674]
![2014-10-20_00003](https://cloud.githubusercontent.com/assets/8431085/4695610/448a530e-580a-11e4-9c72-847decef04c9.jpg)
sent bugreport through ingame as well (BugID:110)

I had no way to exit the channel or re-enter it, I couldn't close it (X didn't respond) and when I pressed General it'd just toss up that screen. Rightclicking and leaving that way also didn't respond.
The only work around was relogging.

Note that I had been disconnected at 3:20ish before and had to re-open sins of a dark age to get back on ironclad's channel. May be nothing, may be something.

**Comment by jseward** [comment]
fixed as of 42131 thanks to manny's logs.
