### ISSUE TITLE
Slag's Tar Ball Hitbox/Texture Misalignment

### ISSUE THREAD

**Issue by Exorcised** [IroncladGames/SinsOfADarkAge#688]
This is actually an older bug that I first saved, and then forgot about, the screenshots for, so you'll have to forgive me for not including the GameID here. However, the bug essentially speaks for itself:

![2014-06-06_00002](https://cloud.githubusercontent.com/assets/7087001/4877882/7d9c3298-62fa-11e4-88ec-e8d23dcd4acc.jpg)

![2014-06-06_00003](https://cloud.githubusercontent.com/assets/7087001/4877883/8144344a-62fa-11e4-9913-e646c662b321.jpg)

Perhaps it has something to do with the skill being laid down in such a tight space, and can consequently be replicated if angled properly against the same forest wall shown above (behind the northern Shaman's spawning plate)?

**Comment by fyst** [comment]
Fixed as of 42935
