### ISSUE TITLE
Leaving a 5v5 primary for another 5v5 primary

### ISSUE THREAD

**Issue by Oblivionn** [IroncladGames/SinsOfADarkAge#690]
First game was on na east, second was on na west.
We ended up leaving the first and starting the second.
![2014-11-09_00001](https://cloud.githubusercontent.com/assets/7982804/4965805/0490c75a-6797-11e4-915d-2016897aa02a.jpg)

**Comment by uncannymanny** [comment]
Game modes popping of the same type of the one you are in should be fixed in 42555. If it happens again, re-open: https://github.com/IroncladGames/SinsOfADarkAge/issues/823
