### ISSUE TITLE
Accept Window Oddness

### ISSUE THREAD

**Issue by Zinovy** [IroncladGames/SinsOfADarkAge#701]
http://cloud-4.steampowered.com/ugc/37481700730402504/3FB4BF3934804291C059EED3277BE931A69F57FE/

There was a queue pop for 5vAI but one person did not accept. Following that, this window appeared. The title says 5v5 but there are only 5 slots. What's more I clicked Accept, but as you can see the Accept button is clickable there - I clicked it again to no effect after this.

**Comment by uncannymanny** [comment]
Gold icon issue should be fixed as of 42114.
