### ISSUE TITLE
[Problem-Bug] Key binding to mouse keys doesn't work

### ISSUE THREAD

**Issue by vasilegherasim** [IroncladGames/SinsOfADarkAge#738]
I have changed the bindings for the inventory item 7 and 8 to mouse keys, but in game it doesn't work.
I tried having bind only the mouse keys, same result.
![key_bind](https://cloud.githubusercontent.com/assets/10153234/5429351/ab3abf0a-83f0-11e4-8be9-8ee0dcb37ad1.jpg)

**Comment by uncannymanny** [comment]
You can now bind inputs to extra mouse buttons.

If your specific mouse hardware isn't working, be sure to post here and reopen this thread.

Thanks!
