### ISSUE TITLE
Broken buff timers

### ISSUE THREAD

**Issue by Oblivionn** [IroncladGames/SinsOfADarkAge#752]
Buff timers don't seem to tick down anymore.
![2014-12-19_00005](https://cloud.githubusercontent.com/assets/7982804/5498549/994e497e-8774-11e4-8238-3f8b2b10aa68.jpg)
![2014-12-19_00006](https://cloud.githubusercontent.com/assets/7982804/5498550/9f30d9ba-8774-11e4-8bb8-75d395e577b6.jpg)

**Comment by Bulletsponge** [comment]
This was a deliberate change, the reasons being:
- it was felt that the duration bar on the buff icon was sufficient to communicate the time remaining
- having a constantly changing value in the tooltip was distracting when trying to read it
- showing the total duration was more helpful from a 'learning the content' perspective.
