### ISSUE TITLE
Hydra Not Considered Large Monster?

### ISSUE THREAD

**Issue by uncannymanny** [IroncladGames/SinsOfADarkAge#760]
Hydra doesn't count towards Nerroth's Hide/Slayer's Mail 25 Large Monster kill amount. Intended?

![2014-12-20_00018](https://cloud.githubusercontent.com/assets/6155683/5514915/f9bf9848-881f-11e4-82e6-d9abb1212db5.jpg)
![2014-12-20_00019](https://cloud.githubusercontent.com/assets/6155683/5514916/f9c14972-881f-11e4-8b14-58292b803e68.jpg)

**Comment by Bulletsponge** [comment]
Hydra is now flagged as a Large monster as of build 41830 (i.e. killing it will stack Nerroth's Hide)

**Comment by uncannymanny** [comment]
Confirmed fixed!

![2015-01-14_00023](https://cloud.githubusercontent.com/assets/6155683/5752519/13c540b0-9c45-11e4-916d-2902ef00be03.jpg)
![2015-01-14_00024](https://cloud.githubusercontent.com/assets/6155683/5752520/13c6b422-9c45-11e4-9876-e867ecb4806a.jpg)
