### ISSUE TITLE
Leaf Stinger Questions/Issues and Camp Analysis

### ISSUE THREAD

**Issue by uncannymanny** [IroncladGames/SinsOfADarkAge#761]
Leaf Stingers are the only underling unit with Magic Resistance. Intended?

![leaf mr](https://cloud.githubusercontent.com/assets/6155683/5514945/a1d54036-8821-11e4-9697-5ff90853dbf4.png)
.
.
.
Leaf Stingers also grant a ridiculous amount of initial XP compared with its peers. Intended? (Verics are bad at math, but these should be right-ish.)

Veric underling: 7.6 xp
Dagger Tusk underling: 16.19 xp
Wood Imp: 10.08 xp
Lesser Wisp: 30.8 xp (makes sense with its longer respawn timer and attachment to Wisp Queen)
Frillspitter: 30.8 xp (makes sense with its longer respawn timer and attachment to Troll)
**Leaf Stinger: a whopping 53 xp each**
.
.
.
Same argument for initial gold:

Veric underling: 3 gold
Dagger Tusk underling: 6 gold
Wood Imp: 4 gold
Lesser Wisp: 8 (makes sense with its longer respawn timer and attachment to Wisp Queen)
Frillspitter: 8 (makes sense with its longer respawn timer and attachment to Troll)
**Leaf Stinger: a whopping 12 each**
.
.
.
Overall camp comparison (initial numbers factoring in base + level 1/non death amount. Bad at math. Hope it's right.):

Veric camp: 193.3 xp and 67 gold (x 2) = 386.6 xp and 134 gold total
Dagger Tusk camp: 203.79 xp and 80.6 gold (x 4) = 815.16 xp and 322.4 gold total
Wood Imp camp: 196.93 - 217.09 xp and 75-83 gold (x 4) = ~826 xp and ~316 gold total
Wisp camp: 390 xp and 110 gold (x 2)= 780 xp and 220 gold total
Troll camp: 390 xp 110 gold (x 2)= 780 xp and 220 gold total
**Leaf Stinger camp:  	336.9 xp and 110.5 gold (x 2)= 673.8 xp and 221 gold total**
.
.
.
So I guess the real question is, do veric camps need a buff? Or should their respawn timers be different for the amount of gold and xp they offer compared to others? Or should Leaf Stinger camps be dialed back to match their most similar peer, the veric camp, in terms of xp and gold? Because at the moment, one Leaf Stinger camp is almost on par with the Wisp/Troll camps (that have a longer cooldown) and is worth almost two veric camps in terms of xp and gold rewards.

(Note: I haven't done any of the Dire unit stuff, so that might even things out maybe? Also, I haven't factored in the relative difficulty of each camp in terms of hp and damage and so on. I haven't actually finished the Troll/Wisp pages yet, so I just sort of did their numbers really quick. Hope they are right! If you have any questions about any of the numbers I came up with, you know where to find me.)

**Comment by Bulletsponge** [comment]
Good find Manny, these values were erroneously left in when the jungle was rebalanced a couple patches ago. This should be fixed in build 41827

**Comment by uncannymanny** [comment]
Down with the Leaf Stingers!

The incorrect gold, exp, and MR on Leaf Stingers has been fixed and the wiki has been updated. Closing!
