### ISSUE TITLE
Does binding secondary mouse keys work?

### ISSUE THREAD

**Issue by writor** [IroncladGames/SinsOfADarkAge#762]
While I can get the keybinding menu to detect my extra mouse keys...
![binding](https://cloud.githubusercontent.com/assets/6934405/5515738/d082c0ce-882c-11e4-98b1-426c7af80e6b.jpg)
...it doesn't work when I try to use them in game. I'm on a Logitech M705, if that makes a difference.

**Comment by uncannymanny** [comment]
You can now bind inputs to extra mouse buttons.

If your specific mouse hardware isn't working, be sure to post here and reopen this thread.

Thanks!
