### ISSUE TITLE
[Problem-Bug] 5 vs. AI game already accepted

### ISSUE THREAD

**Issue by vasilegherasim** [IroncladGames/SinsOfADarkAge#770]
A popup for 5 vs. AI game is already filled up with accept, i pressed accept but nothing happened, screen atached.
![5vsai](https://cloud.githubusercontent.com/assets/10153234/5544844/85c12c7a-8b19-11e4-9ffe-a3a20ae0afac.jpg)

**Comment by uncannymanny** [comment]
Gold icon issue should be fixed in 42114.
