### ISSUE TITLE
Missing AoE indicator

### ISSUE THREAD

**Issue by Oblivionn** [IroncladGames/SinsOfADarkAge#776]
If the start point of an ability is in the brush, it's area indicator isn't shown, but slags tar ball area can leave the brush, but still have no indicator.
![2014-12-29_00001](https://cloud.githubusercontent.com/assets/7982804/5567990/038e1a26-8fa4-11e4-8a66-2d5a0c6285d2.jpg)

**Comment by fyst** [comment]
Fixed as of 41898
