### ISSUE TITLE
Nerroths fangs death summary missing image

### ISSUE THREAD

**Issue by Oblivionn** [IroncladGames/SinsOfADarkAge#779]
![2014-12-31_00001](https://cloud.githubusercontent.com/assets/7982804/5585802/09e3893c-910d-11e4-99f2-f038bd585d17.jpg)

**Comment by Bulletsponge** [comment]
Fixed in build 41821

**Comment by uncannymanny** [comment]
Confirmed fixed.

![nerroth fang](https://cloud.githubusercontent.com/assets/6155683/5753016/9d0e6f86-9c4f-11e4-9446-c502c4949272.png)
