### ISSUE TITLE
Persisting skeletons

### ISSUE THREAD

**Issue by Oblivionn** [IroncladGames/SinsOfADarkAge#784]
![2015-01-02_00002](https://cloud.githubusercontent.com/assets/7982804/5594728/a155affc-92ac-11e4-8d98-168e4198d860.jpg)
If a skeleton spawns right as the quest ends, it'll stay around until it dies

**Comment by Bulletsponge** [comment]
Fixed in build 41825

**Comment by uncannymanny** [comment]
Should be fixed. Is very hard to verify due to the 50% chance of them spawning and due to approximate length of the quest item bar.

If it happens again somehow, feel free to reopen.
