### ISSUE TITLE
Ingame screen mis-name

### ISSUE THREAD

**Issue by Oblivionn** [IroncladGames/SinsOfADarkAge#794]
Your 6 item slots tooltip says that they are consumable slots, while the 2 consumables slots say that they are item slots.

**Comment by uncannymanny** [comment]
Could you walk me through where you are seeing this?

![2015-01-05_00001](https://cloud.githubusercontent.com/assets/6155683/5613491/0c527daa-94b3-11e4-8676-fcaa2bc67958.jpg)
![2015-01-05_00007](https://cloud.githubusercontent.com/assets/6155683/5613490/0c514fc0-94b3-11e4-9c56-a5597513a3d9.jpg)

**Comment by Oblivionn** [comment]
Yeah, that was what I was talking about.
I ss' d it, but didn't bother since steam removed the cursor.

**Comment by Bulletsponge** [comment]
Fixed in build 41818

**Comment by uncannymanny** [comment]
Looks fixed

![2015-01-14_00006](https://cloud.githubusercontent.com/assets/6155683/5752368/a85a4c9c-9c41-11e4-8cb5-7b6f7e9d4a28.jpg)
![2015-01-14_00007](https://cloud.githubusercontent.com/assets/6155683/5752367/a8580220-9c41-11e4-8142-1f55c7c00b6b.jpg)
