### ISSUE TITLE
Ziri pre-game lobby

### ISSUE THREAD

**Issue by Oblivionn** [IroncladGames/SinsOfADarkAge#796]
In pregame, hovering over someone who's selected Ziri shows Hero: Classic, instead of the skin/hero name.

**Comment by Bulletsponge** [comment]
Fixed in build 41816

**Comment by xAzta** [comment]
Same to one of Xeros skin, the blood one maybe, dont really remember.

**Comment by uncannymanny** [comment]
Every hero skin combination is good except for:

![solarus tbd](https://cloud.githubusercontent.com/assets/6155683/5733588/43ae81a6-9b73-11e4-8556-0b07a4ddffee.png)

**Comment by Bulletsponge** [comment]
Solarus Serewyn fixed as of build 41964

**Comment by uncannymanny** [comment]
Will the fix there also fix it here?

![tbd](https://cloud.githubusercontent.com/assets/6155683/5793019/8ae2fad4-9f01-11e4-976a-876693fd7513.png)

**Comment by uncannymanny** [comment]
Looks fixed!

![ola 2](https://cloud.githubusercontent.com/assets/6155683/5859183/60f2801e-a226-11e4-8848-c7b83670d9cb.png)
![ola](https://cloud.githubusercontent.com/assets/6155683/5859184/60f8134e-a226-11e4-83d8-58d5091b93bb.png)
