### ISSUE TITLE
[Suggestion] - Twitch streams

### ISSUE THREAD

**Issue by vasilegherasim** [IroncladGames/SinsOfADarkAge#799]
I really think that there should be some audio recording option for twitch.
For example, i want to listen to music while streaming, but then will have to deal with copyright laws, so an option for twitch to record only game audio.

**Comment by uncannymanny** [comment]
Since the newest patch hit, in-game screen capture is no longer supported. It's up to external software to determine what is captured.

**Comment by kaylenday** [comment]
I wish that u didn't have to download anything to stream, plz make something like that

**Comment by vasilegherasim** [comment]
I use now OBS and VAC, and is working like a charm, you can close the case.

**Comment by uncannymanny** [comment]
Soada requires external software to capture screen footage.

The benefit of linking of your Soada and Twitch accounts is it lets you access your Twitch chat while in-game and also makes you eligible for item gifts if you are present when official streamers give away a Twitch chest.

You can read more about Soada's Twitch integration here: http://soada.wikia.com/wiki/Twitch_Integration

Thanks for the update vasilegherasim.

Closing now.
