### ISSUE TITLE
Score sheet non-visible players can't give mouse over information

### ISSUE THREAD

**Issue by Tugimus** [IroncladGames/SinsOfADarkAge#808]
In tab score sheet, when a player is not in vision of your team, even though you can see the information of the items, glyphs and kit from the last time they were seen, you cannot get mouse over information of them.

**Comment by writor** [comment]
Patch 42114:

"Fixed bug where you didn't get a tooltip if you hovered your cursor over an undetected Hero's inventory items, Glyphs or Hero Kit."

http://steamcommunity.com/app/251970/discussions/7/613948093873549203/
