### ISSUE TITLE
[Problem-Bug] Friendlist button not active after match ends

### ISSUE THREAD

**Issue by vasilegherasim** [IroncladGames/SinsOfADarkAge#809]
The friendlist button is not active, after a match, still shows 6 friends online.
![friend list _not](https://cloud.githubusercontent.com/assets/10153234/5689326/d9a87fe6-986b-11e4-83e5-a3ccdbfc8986.jpg)

**Comment by uncannymanny** [comment]
Ah, Steam went down in this scenario.

It happens some times.

Logging out and back in should fix it (unless Steam is down down.)

**Comment by uncannymanny** [comment]
If it happens again, check if Steam has No Connection.

If it's not a Steam issue, feel free to re-open.
