### ISSUE TITLE
Hypothetical Virtue Issue and Fellowship Bundle

### ISSUE THREAD

**Issue by uncannymanny** [IroncladGames/SinsOfADarkAge#815]
Let's say you give Bob a Fellowship Bundle and you play a few matches.

Eventually math gets the better of you and you end up in this situation:

![virtue example](https://cloud.githubusercontent.com/assets/6155683/5694877/0f69bf50-994d-11e4-805d-a20e95b7ad0f.png)

You just need one more point to reach Virtue level 4.

But lo and behold Bob finally gets level 10, thus giving you your free Virtue level.

What would happen in this case?

Would you go from level 3 to level 4 with 0/250 points, essentially wasting the free virtue level?

Or will your points carry over so that it's 250/250 again, so you just need one more point to get level 5?

**Comment by Oblivionn** [comment]
Getting a fellowship just adds a level, so it would go to lvl 4 250/250, if i'm not mistaken

**Comment by Bulletsponge** [comment]
Oblivionn has it right. Additionally, we fixed the bug that was causing 250/250 not to roll you over to the next level, so that shouldn't happen anymore either.

**Comment by uncannymanny** [comment]
Thanks for the reply!

Glad I pointed it out and got the bug fixed then!
