### ISSUE TITLE
Certain Key Bindings not working in game.

### ISSUE THREAD

**Issue by reaven1123** [IroncladGames/SinsOfADarkAge#817]
I have a naga hex that has two extra mouse buttons under the scroll wheel. They register as ExtraMouse0 and ExtraMouse1 in the key bindings menu. I set the ExtraMouse0 to be my recall key, but when I tried to use it in game, it woul not register. I had the same thing happen with the ExtraMouse1.

**Comment by uncannymanny** [comment]
Good find. I think enhanced mouse support is a widely requested feature. I unfortunately do not have an update on its status though.

Similar issues:

https://github.com/IroncladGames/SinsOfADarkAge/issues/292
https://github.com/IroncladGames/SinsOfADarkAge/issues/738
https://github.com/IroncladGames/SinsOfADarkAge/issues/762

**Comment by uncannymanny** [comment]
You can now bind inputs to extra mouse buttons.

If your specific mouse hardware isn't working, be sure to post here and reopen this thread.

Thanks!
