### ISSUE TITLE
Joining Match From Try Hero Failed to Join

### ISSUE THREAD

**Issue by uncannymanny** [IroncladGames/SinsOfADarkAge#820]
Note for this first example, both players were in Try Hero.

Queue, then go into try hero.

![2015-01-13_00007](https://cloud.githubusercontent.com/assets/6155683/5732749/78b3be6a-9b65-11e4-8cd5-36ee964047fa.jpg)

Accept when prompted.
![2015-01-13_00008](https://cloud.githubusercontent.com/assets/6155683/5732750/78c71cb2-9b65-11e4-896a-a249a080b9f6.jpg)
![2015-01-13_00009](https://cloud.githubusercontent.com/assets/6155683/5732751/78cb17cc-9b65-11e4-8da5-e7bcb2df0eea.jpg)
![2015-01-13_00010](https://cloud.githubusercontent.com/assets/6155683/5732752/78cc793c-9b65-11e4-9188-bae5e423f76d.jpg)
.
.
.
I tried again:
Note: the other player will be in lobby (the other player was at front end, not try hero). However, you will still be in try hero and it won't pop for you, thus leading to a dodge on your end:
His screen (for about 10 seconds):
![654ae974daf0e8bdb530a2a88629c80a0930285bad6d0077aa pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/6155683/5732973/6a9fce5a-9b69-11e4-9675-6ebf12500eab.jpg)
.
.
.
Your eventual screen:
![2015-01-13_00013](https://cloud.githubusercontent.com/assets/6155683/5732840/4e8a2bb8-9b67-11e4-8621-8bf439f8b8e6.jpg)
.
.
.
.
Works okay from a Custom game though: (However the dual gold icon before accepting is still an issue)
![2015-01-13_00011](https://cloud.githubusercontent.com/assets/6155683/5732788/541f5950-9b66-11e4-9c58-044f968794b7.jpg)
![2015-01-13_00012](https://cloud.githubusercontent.com/assets/6155683/5732787/541de0ac-9b66-11e4-81ab-96942b96a073.jpg)

**Comment by jseward** [comment]
both bugs fixed as of 42015
