### ISSUE TITLE
Attribute Scaling Grammar

### ISSUE THREAD

**Issue by uncannymanny** [IroncladGames/SinsOfADarkAge#821]
Get to this screen by holding tab and mousing over the Hero Kit Slot.

![fewer](https://cloud.githubusercontent.com/assets/6155683/5733010/ee1c54f6-9b69-11e4-84dc-40e7f67bf2ab.png)

Less should be fewer.

http://i.imgur.com/zV9wRQ7.gifv

(sorry I had to)

**Comment by writor** [comment]
The new string will read: "All hero stats for this player will be scaled up since they have fewer Attribute Points than other players in the match." Thanks Manny!

**Comment by uncannymanny** [comment]
Thank Weird Al! :P
