### ISSUE TITLE
Game popping for type you're already in

### ISSUE THREAD

**Issue by Oblivionn** [IroncladGames/SinsOfADarkAge#823]
![2015-01-14_00001](https://cloud.githubusercontent.com/assets/7982804/5734029/240aacba-9c01-11e4-9173-c3c5e8a9a888.jpg)
Still seems to happen as of newest patch.

**Comment by uncannymanny** [comment]
Dang. Good catch.

https://github.com/IroncladGames/SinsOfADarkAge/issues/744

and https://github.com/IroncladGames/SinsOfADarkAge/issues/690

(Just for admin reference

**Comment by uncannymanny** [comment]
Game modes popping of the same type of the one you are in should be fixed in 42555. If it happens again, can always re-open.
