### ISSUE TITLE
Match Making Not Remembering Game Types

### ISSUE THREAD

**Issue by uncannymanny** [IroncladGames/SinsOfADarkAge#830]
I like to add all six options so I can get an idea of which modes are getting queued for:

![2015-01-14_00001](https://cloud.githubusercontent.com/assets/6155683/5752325/fb6e9934-9c40-11e4-9e98-feb774743fd7.jpg)
.
.
.
However, upon logging out and back in, I realize that I have to re-add these each time I log in:

![2015-01-14_00003](https://cloud.githubusercontent.com/assets/6155683/5752330/08dea3ac-9c41-11e4-9431-b0a49b92dcde.jpg)

**Comment by Oblivionn** [comment]
Matchmaking filters are synced to the steam cloud i've noticed, do you have it disabled?

**Comment by uncannymanny** [comment]
It wasn't doing it for a while, but it finally kicked in and remembered the 6 settings.

But now if I change it again, it will just default to the 6 settings.

Rebooting Steam doesn't seem to do it. No idea how to force a Steam Cloud update.

**Comment by Oblivionn** [comment]
From what I've found, it doesn't seem to save or load properly, sometimes when i log in, it's blank, sometimes it's defaulted to 5v5 normal and 2v2 scrimmage, and sometimes it actually has what i've setup.

**Comment by uncannymanny** [comment]
Fixed in 42114
