### ISSUE TITLE
path to ascension

### ISSUE THREAD

**Issue by Oblivionn** [IroncladGames/SinsOfADarkAge#838]
When doing path to ascension, you can't see the progress bar when undetected since last patch, but you can still hear the sound of them gathering at each checkpoint.
The beacons seem to have a small sight range shared with the heroes, which can detect heroes, is this intended?

**Comment by uncannymanny** [comment]
The sound issue may or may not be intended.

The visibility: I think it is intended: https://github.com/IroncladGames/SinsOfADarkAge/issues/505

**Comment by braffles** [comment]
The sound issue is not intended. Should not be hearing the sound unless you have visibility of the hero that is capturing the beacon.

**Comment by fyst** [comment]
Fixed as of April 7 2015 (Perforce is down so I'll have to get the changelist from the date later).
