### ISSUE TITLE
Tower's health disappears

### ISSUE THREAD

**Issue by elvensmile** [IroncladGames/SinsOfADarkAge#843]
Tower Siege Quest. Enemy tower health disappears from quest sign (thing in the top of screen)
http://www.twitch.tv/elvensmile/c/5893347 (2 minutes video)

**Comment by uncannymanny** [comment]
Hmm . . . is that from earlier today, or from an older session before the hotfix?

**Comment by elvensmile** [comment]
It is just from that stream you watched with SolarSpish

**Comment by uncannymanny** [comment]
Dang. Okay. Thank for the reply.

I guess the hotfix from the patch notes is still acting up then.

Do you recall which gameID that was?

**Comment by elvensmile** [comment]
Game ID 147646

**Comment by uncannymanny** [comment]
Kk thanks!

:)

**Comment by fyst** [comment]
Fixed a few patches ago.
