### ISSUE TITLE
Crystalline Barrier Clarification

### ISSUE THREAD

**Issue by uncannymanny** [IroncladGames/SinsOfADarkAge#846]
Foxhound brought this up.

Crystalline barrier tooltip is a little confusing at first.

"Absorbs a fraction of the Magic Damage dealt to you and converts it into additional Mana."

Magic Damage Blocked: + 5%
Mana Restored: + 30% 

The tootltip makes it sound like that the fraction is being converted, but in my tests, it's the total magic damage* that is converted.

I suggest something like "Absorbs a fraction of the Magic Damage dealt to you and converts [a percentage of the total Magic Damage] into additional Mana." (I think that's correct. I wanted to use "restore" but I don't think "restore into mana" is a thing. The only problem with using "total Magic Damage" is I don't know what happens in team fights or if you get chained by multiple abilities.)

Here is what I did to verify that 30% of the total Magic Damage was being converted into Mana.

(Three points in Fire Grenade)
![fire grenade](https://cloud.githubusercontent.com/assets/6155683/5788620/352b1b28-9e0f-11e4-8592-560c2e441940.png)
![2015-01-17_00003](https://cloud.githubusercontent.com/assets/6155683/5788617/2c91e226-9e0f-11e4-9618-a8c7ba3d2f06.jpg)
(30% of 220)
.
.
.
![the big one](https://cloud.githubusercontent.com/assets/6155683/5788623/4b24faac-9e0f-11e4-8d77-e3cf2af8e326.png)
![2015-01-17_00008](https://cloud.githubusercontent.com/assets/6155683/5788618/2c92dd2a-9e0f-11e4-8210-cfd7721b9a0c.jpg)
(30% of 225)

Note: I know one of the patch notes added that "Crystalline Barrier will restore more mana for a given amount of magic damage recieved since the restore is now based on damage received before MR reduces it instead of after," but not everyone checks them or the wiki.

*I forgot to test if it factors in special power items. I think it does though in my tests with Grugg vs Lassidar Golem in Try Hero.

**Comment by writor** [comment]
I think the original text read something like, "and converts that into six times the Mana," which sounded overly informal/colloquial. In revising things, I suppose we lost some clarity. Changes will show up in the next patch.
