### ISSUE TITLE
Blooddrop Lore Text

### ISSUE THREAD

**Issue by uncannymanny** [IroncladGames/SinsOfADarkAge#849]
![blooddrop](https://cloud.githubusercontent.com/assets/6155683/5792759/687cdbe6-9ef6-11e4-8840-c15f59ac6582.png)

Bloodrop should be Blooddrop here.

**Comment by writor** [comment]
This has been fixed behind the scenes. There are a few extra steps before the fix will appear in the live build.

**Comment by writor** [comment]
Now it's officially been fixed, Rev 42047. Thanks Manny!

**Comment by uncannymanny** [comment]
I will miss calling it bloo-drop. (blew-drop)

Back to blood-drop now! :)
