### ISSUE TITLE
Capitalization Issue

### ISSUE THREAD

**Issue by uncannymanny** [IroncladGames/SinsOfADarkAge#850]
![capital](https://cloud.githubusercontent.com/assets/6155683/5792778/b654ddea-9ef7-11e4-8fb9-35a2a300ee98.png)

The "O" in "Items owned" should probably capitalized to match the other similar tooltips (which are also capitalized.)

**Comment by writor** [comment]
Thanks Manny, this will be fixed in the next patch.

**Comment by uncannymanny** [comment]
Found another!

![capitaliz](https://cloud.githubusercontent.com/assets/6155683/5972440/6bd64d60-a827-11e4-9b2b-47cebe8a1474.png)

**Comment by writor** [comment]
All strings are currently being reviewed. Thank you for your report, I don't have to find this one myself now!
