### ISSUE TITLE
[Problem-Bug] Search criteria is not stored after restarting the game

### ISSUE THREAD

**Issue by vasilegherasim** [IroncladGames/SinsOfADarkAge#851]
If you add another match search criteria, is not stored in the Play menu.
For example: I added the 5vsai Normal, after restart there is no more.
![untitled](https://cloud.githubusercontent.com/assets/10153234/5792921/df6258d0-9f37-11e4-8563-3e79d3411327.jpg)

**Comment by uncannymanny** [comment]
Another good catch.

Similar issue here: https://github.com/IroncladGames/SinsOfADarkAge/issues/830

**Comment by uncannymanny** [comment]
Should be fixed in 42114.

Thanks for the report!
