### ISSUE TITLE
Online Status, PM's, and Impersonation Analysis

### ISSUE THREAD

**Issue by uncannymanny** [IroncladGames/SinsOfADarkAge#852]
Issue 1: Online vs Offline PM's.

You will not receive in-game front end messages from non-friends if your Steam status is set to Offline. Intended? This means I have probably missed a bunch of pm's from people who I am not friends with.

When receiver is online:
Manny's screen:
![2015-01-19_00006](https://cloud.githubusercontent.com/assets/6155683/5808895/85295a3e-a000-11e4-81aa-9fe3513d799e.jpg)
(Note, it still shows Totally Not Manny as the impostor manny the veric king from the examples below due to the Steam cache not refreshing)
.
Totally Not Manny (TNM)'s screen:
![manny online](https://cloud.githubusercontent.com/assets/6155683/5808902/99e34886-a000-11e4-8752-904a264f18db.png)
.
.
.
When receiver is offline:
Manny's screen
![2015-01-19_00007](https://cloud.githubusercontent.com/assets/6155683/5808916/c8866df8-a000-11e4-8375-9a88e3a79364.jpg)
(Note, it still shows Totally Not Manny as the impostor manny the veric king  from the examples below due to the Steam cache not refreshing)
.
TNM's screen:
![manny offline](https://cloud.githubusercontent.com/assets/6155683/5808921/d48653de-a000-11e4-805c-33d35fc28f10.png)

Notice that the message that Manny sent was not received by the offline TNM.

Should offline people get PM's? . . . This I will get back to. But first, there's a little issue we have to get to with the PM system as a whole.

Issue 2. Dev/Mod Impersonation and PM's.

Impersonating a mod is pretty easy. While I touched upon this here: https://github.com/IroncladGames/SinsOfADarkAge/issues/536, it can get much worse with PM's.

To impersonate a mod, it's pretty simple. Just change your name. Now the benefit of the General Chat is that mods show up as pink and fabulous. But in PM's . . . they do not.

Now finding people is an issue. The easiest way to find someone is to right click their name and send message. This sort of exposes you to scrutiny since you have to find people in General. When the player base gets larger, it might be easier to "hide in plain sight" while in General.

Here's what happens when you receive a message from an impostor.

![3b2e47cfd4bb154dbe7e1dc93db7e26db69e5699a903152da9 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/6155683/5808974/79a5dd58-a001-11e4-90a6-8a7c58d62be8.jpg)

The real and fake manny look exactly alike. And the worst thing is you cannot block or access their Steam or Game profile this way. So anyone at this point in time can pretend to be a dev or mod in a PM as long as they can send a message to you.

But here's where it gets scary and where smart people will be able to find victims, but it requires work on their part. They basically just need to play one game with a popular player (before they begin the impersonation process.) 

In this screenshot, we, the impostor just need to play one game with a popular person. Manny's popular. Let's choose him.
![2015-01-19_00009](https://cloud.githubusercontent.com/assets/6155683/5809308/04327802-a005-11e4-86fe-f41c7a413b12.jpg)
.
.
.
Then I the impostor just have to view that game to get to Manny's game history.
![dd1b2f8af0d95c49f497d481bc1651c41b90d34ff4c0589fd6 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/6155683/5809428/62c706ca-a006-11e4-88fd-c69420242833.jpg)

.
.
.
From here, he can basically send impostor messages to anyone Manny has played with recently and just leapfrog to other players by viewing their game profile, basically turning into a sick six degrees of Kevin Bacon game.
Oh hey there Crugg. Let me as impostor manny curse you out and potentially get the real manny in lots of trouble.
![2015-01-19_00012](https://cloud.githubusercontent.com/assets/6155683/5809320/1c7acdec-a005-11e4-8944-6f23c5e29cd3.jpg)
.
.
.
And the scariest thing? You won't be able to find who is sending it or block them. They will just keep sending you fake impostor messages. And you won't be able to find them anyway because even if you scour every game you've been in via game history looking for them, it will just show their old name.

![2015-01-19_00013](https://cloud.githubusercontent.com/assets/6155683/5809345/70dddaf0-a005-11e4-97a9-d88d0e7a4187.jpg)

A smart impostor simply has to avoid general chat or close it as fast as possible upon logging in and not play any games with their new name to avoid detection.

So back to the offline, online message debate. Should offline people receive front end messages? I don't know. I just know that as long as the victim is online, an impersonator can potentially mess with them.

![2015-01-19_00005](https://cloud.githubusercontent.com/assets/6155683/5809350/82b42752-a005-11e4-803a-e9295de1c6b4.jpg)

The easiest solution is to color code dev and mod names in regards to pm's.

Even though the color coding will help stop impersonators, leapfrogging pm's via spam can still be a problem. Therefore, the second easiest solution is to add some sort of method to trace back a PM to a game or Steam profile, so that you can report spam or other abuse.

Thanks for reading!

**Comment by writor** [comment]
There is now a warning message when you receive a whisper from someone who isn't on your Friends list. It warns you that their identity cannot be verified. This should help with potential imposter-dom. So...issue 2 solved? (Pending a test in the next patch.)

**Comment by jseward** [comment]
Fixed as of 42070

1. There is now a red warning message when receiving whispers from non-friends.
2. You can now right click whisper chat and view either steam or game profiles of the account.
3. Steam blocks the chat to offline players so there is nothing we can do about that.

thanks manny!

**Comment by uncannymanny** [comment]
Me, myself, and I thank you for looking into it! :)
