### ISSUE TITLE
[Problem-Bug] Another 5vs5 popup while match loading

### ISSUE THREAD

**Issue by vasilegherasim** [IroncladGames/SinsOfADarkAge#853]
Another 5vs5 popup while match loading.
![untitled](https://cloud.githubusercontent.com/assets/10153234/5809454/51bd2586-a041-11e4-9869-25a043737263.jpg)

**Comment by uncannymanny** [comment]
Ah, it is unfortunate that this is still happening with the new matchmaker.

Thanks for the report.

Admin reference: https://github.com/IroncladGames/SinsOfADarkAge/issues/823

**Comment by vasilegherasim** [comment]
And that popup just popped abou 5times before the match to begin.

**Comment by Tugimus** [comment]
Is it possible to get the log file from this occurance sent to support @ironcladgames.com, it would help greatly :)

**Comment by vasilegherasim** [comment]
Sent.

**Comment by uncannymanny** [comment]
Game modes popping of the same type of the one you are in should be fixed in 42555. If it happens again, re-open: https://github.com/IroncladGames/SinsOfADarkAge/issues/823
