### ISSUE TITLE
mouse hotkeys

### ISSUE THREAD

**Issue by DocSam** [IroncladGames/SinsOfADarkAge#856]
Hi,

i have a sidewinder mouse, and when i bind some keys in the options (for example quick cast) , then in game it does not work.

Thank you

**Comment by uncannymanny** [comment]
Good suggestion!

It's a pretty popular request!

Similar issues for admin purposes: https://github.com/IroncladGames/SinsOfADarkAge/issues/762 https://github.com/IroncladGames/SinsOfADarkAge/issues/738 https://github.com/IroncladGames/SinsOfADarkAge/issues/292

**Comment by DocSam** [comment]
ops...sorry, i have not searched properly xD

**Comment by uncannymanny** [comment]
It's fine.

I think some mouse buttons work if they were originally a key that can be rebound, but other more specialized ones might not work.

It's always good to get more reports of various mouse hardware, so the devs have an idea of which mice are having issues.

**Comment by DocSam** [comment]
this is my hardware 
http://www.microsoft.com/hardware/_base_v1//products/sidewinder-x8-mouse/gm_swmx8_ci.jpg

very simple and standard key; the middle mouse button and the other 2 on the side

**Comment by uncannymanny** [comment]
Thanks for the report!

Hopefully as Early Access continues, more hardware can be supported!

**Comment by uncannymanny** [comment]
You can now bind inputs to extra mouse buttons.

If your specific mouse hardware isn't working, be sure to post here and reopen this thread.

Thanks!
