### ISSUE TITLE
Recipes - Material Color Coding

### ISSUE THREAD

**Issue by writor** [IroncladGames/SinsOfADarkAge#859]
Currently when you mouse over a recipe, materials that you've successfully gathered appear as green text, and materials you still need appear red. See image below:

![recipe](https://cloud.githubusercontent.com/assets/6934405/5843270/3f8bcdd4-a160-11e4-8d73-455d4158c9d2.jpg)

My suggestion is, it may be useful to add a third color to the mix (orange maybe?), to indicate materials that you have begun to gather, but don't have enough of. See Stinging Vines, in the screenshot above. Glancing at the recipe, it's easy to assume that the Life Seed is the ONLY progress that has been made towards earning the skin, which is a bit discouraging and misleading.

Thanks!

**Comment by uncannymanny** [comment]
Neat idea. I like it!

**Comment by xAzta** [comment]
Indeed, good one :)

**Comment by jseward** [comment]
I like this idea so much... I bought the company. Spatula City!

Fixed as of 42645
