### ISSUE TITLE
Portal scroll

### ISSUE THREAD

**Issue by Oblivionn** [IroncladGames/SinsOfADarkAge#870]
You can sell a portal scroll while it's channeling and it'll cancel the channel, but the teleporting buff will stay, and you will teleport at the end of the duration at a reduced cost.

Edit: using a scroll disables refunds.

**Comment by uncannymanny** [comment]
Good catch.

Basically a reduced cost portal scroll with this (if you remember to do it.)

**Comment by fyst** [comment]
Fixed as of 42694
