### ISSUE TITLE
[Problem-Bug] Game id not shown in match history

### ISSUE THREAD

**Issue by vasilegherasim** [IroncladGames/SinsOfADarkAge#877]
The gameid and time of the game are not shown in game history, but there are shown on the tooltip.
![untitled](https://cloud.githubusercontent.com/assets/10153234/5891673/f04d52ca-a4ab-11e4-9e09-a6cfaf7cd4bf.jpg)

**Comment by uncannymanny** [comment]
Good eye.

Similar issue for admin reference.

**Comment by jseward** [comment]
Fixed as of 42644
