### ISSUE TITLE
Searching for 5vs5 or 2vs2 but suddently a popup come from 1vs1 if i not accept 1vs1 then my search stop and i need to search gain

### ISSUE THREAD

**Issue by uddin9live** [IroncladGames/SinsOfADarkAge#888]

**Comment by uncannymanny** [comment]
Could you take a screenshot of your Play screen with all the game types you choose when searching for a match and upload it here?

If you could, have your cursor hover over "Search for Match" and use F12 to take the screenshot.

You can find your Steam Screenshots by pressing Shift+Tab while in-game. If you need to enable the Steam overlay, you can go here for reference: http://soada.wikia.com/wiki/Enabling_the_Steam_Overlay

**Comment by uncannymanny** [comment]
Most importantly, if this issue happened in this game session (that is if you are still playing and haven't logged out), press Escape and Send Bug Report.

You can put the bug tracker ID here for reference.

**Comment by uddin9live** [comment]
http://steamcommunity.com/sharedfiles/filedetails/?id=385653621

**Comment by uddin9live** [comment]
ok I will report from the game also

**Comment by uncannymanny** [comment]
Ah, thank you for the reply.

Were you searching for just 5v5 and 2v2 when the 1v1 popped?

Is it possible that you may have also been searching for a 1v1, or is that 1v1 a new addition since the issue occurred?

**Comment by uddin9live** [comment]
no i did not search for 1vs1

**Comment by uncannymanny** [comment]
Good to know, thanks again.

If the bug occurred this game session, then yes, the Escape->Send Bug Report will really help.

Thanks!

**Comment by uddin9live** [comment]
Yesterday what happened that . i have joined a team 2vs2  everyone selection their hero , suddenly a popup came to join for 5vs5  and them i have accepted for 5vs5 , it is should not be like that while i selecting a hero for 2vs2

**Comment by uncannymanny** [comment]
Ah, I believe what happened in yesterday's case is you were in Scrimmage 2v2.

Scrimmage games are games to pass the time while waiting for a Normal game type to spawn.

The idea is you play a Scrimmage 1v1 or 2v2 while waiting for your 5v5 or 5 vs ai. When the 5v5 or 5 vs ai is ready, you can join directly from the Scrimmage 1v1 or 2v2.

Now in that picture you sent, I notice that Duel 1v1 is one of the choices. Did you add that choice recently, after the 5v5, 2v2 issue occurred? Or was the Duel 1v1 choice always there?

**Comment by fyst** [comment]
Matchmaking was completely rewritten
