### ISSUE TITLE
[Problem-Bug] Match history is wrong, and still no game id on last game

### ISSUE THREAD

**Issue by vasilegherasim** [IroncladGames/SinsOfADarkAge#890]
With the last update.
![history](https://cloud.githubusercontent.com/assets/10153234/6050116/abd17c44-acc5-11e4-9f11-afb716e2ca67.jpg)

**Comment by uncannymanny** [comment]
Ah . . . Unfortunately, everyone's client-side game history and hero kits are being wiped.

As for the ???? still being an issue, good eye.

See also https://github.com/IroncladGames/SinsOfADarkAge/issues/877 and https://github.com/IroncladGames/SinsOfADarkAge/issues/869

**Comment by vasilegherasim** [comment]
Now is ok, after the newest patch :)

**Comment by uncannymanny** [comment]
The )??? is still an issue as of the latest patch if you view someone's game profile.

![2015-02-05_00001](https://cloud.githubusercontent.com/assets/6155683/6059388/e15aebd2-acfe-11e4-95c3-ef5e8a18b68e.jpg)

**Comment by jseward** [comment]
Fixed as of 42644
