### ISSUE TITLE
Portal in advanced casting in controls has icon of bulwark

### ISSUE THREAD

**Issue by Oblivionn** [IroncladGames/SinsOfADarkAge#891]

**Comment by uncannymanny** [comment]
Good eye.

![2015-02-04_00022](https://cloud.githubusercontent.com/assets/6155683/6054698/e0468b2e-acbe-11e4-8e9b-2b5d384ece21.jpg)

**Comment by Rygel6** [comment]
missing and incorrect icons fixed as of 42573 
"shop item" typo fixed as of 42574
Detection Ward name fixed as of 42575
