### ISSUE TITLE
Pause Tooltip Question

### ISSUE THREAD

**Issue by uncannymanny** [IroncladGames/SinsOfADarkAge#894]
![2015-02-07_00001](https://cloud.githubusercontent.com/assets/6155683/6092419/fd621edc-aeab-11e4-995d-b6d04a6ec1b2.jpg)

Is the X amount supposed to be a number or a placeholder?

Do pause amounts change depending on game mode?

**Comment by writor** [comment]
It's a placeholder that was never updated, whoops.
