### ISSUE TITLE
Potential Twitch Mobile Issue

### ISSUE THREAD

**Issue by uncannymanny** [IroncladGames/SinsOfADarkAge#897]
![reward twitch](https://cloud.githubusercontent.com/assets/6155683/6098088/a04e014c-afa1-11e4-9f72-226fb7f601f6.PNG)

Are Twitch Mobile users exempt from gifts?

Isn't the portrait an eligibility of sorts?

**Comment by jseward** [comment]
He should be eligible, it just does a lookup on username. Perhaps Perfectstorm91 never wired up twitch to his ico account?

**Comment by uncannymanny** [comment]
Yep manny no smart good.
