### ISSUE TITLE
Crafted By X Tooltip Issue

### ISSUE THREAD

**Issue by uncannymanny** [IroncladGames/SinsOfADarkAge#901]
User Ogresbane crafted Blooddrop Ermuk, but it's missing the Crafted By tooltip like his other crafted items.

![251970_screenshots_2015-02-10_00003](https://cloud.githubusercontent.com/assets/6155683/6133840/d13f2d14-b12a-11e4-878f-f6eb5c55b5d5.jpg)

![251970_screenshots_2015-02-10_00002](https://cloud.githubusercontent.com/assets/6155683/6133839/d13b266a-b12a-11e4-80e7-137d31b57529.jpg)

Is it because it's 8 months old?

**Comment by jseward** [comment]
Unfortunately old crafted skins won't have that information, got added only a few patches ago.
