### ISSUE TITLE
[Problem-Bug] Twitch in-game chat line misplaced

### ISSUE THREAD

**Issue by vasilegherasim** [IroncladGames/SinsOfADarkAge#903]
The in-game Twitch chat is moved to the left as in the screen attached.
![tritch_chat](https://cloud.githubusercontent.com/assets/10153234/6157664/fbd7679a-b24b-11e4-96d9-8bc3cf316b0c.jpg)

**Comment by uncannymanny** [comment]
Good eye.

The others are wonky.

It's interesting comparing them all:

![2015-02-11_00003](https://cloud.githubusercontent.com/assets/6155683/6158103/2884ddc2-b215-11e4-8466-b357a76fb87b.jpg)
![2015-02-11_00004](https://cloud.githubusercontent.com/assets/6155683/6158102/2883516e-b215-11e4-8fc6-9b9fbcb657cb.jpg)
![2015-02-11_00006](https://cloud.githubusercontent.com/assets/6155683/6158104/28887540-b215-11e4-84b3-be62ffc13b49.jpg)

**Comment by fyst** [comment]
No longer relevant. New chat system incoming.
