### ISSUE TITLE
[Problem-Bug] 5 vs. AI game keeps poping in a 5vs5 match

### ISSUE THREAD

**Issue by vasilegherasim** [IroncladGames/SinsOfADarkAge#904]
5 vs. AI game keeps poping in a 5vs5 match.
![5vs5](https://cloud.githubusercontent.com/assets/10153234/6178805/418c0d8e-b31b-11e4-8960-2d79839e4d37.jpg)

**Comment by jseward** [comment]
can I get the gameId and your accounId and/or playername? thanks.

**Comment by uncannymanny** [comment]
http://www.twitch.tv/mandark_a/b/623889303

Gameid 180740

76561198022721525

**Comment by jseward** [comment]
fixed as of 42756

http://jseward.github.io/2015/02/13/fixing-of-bug-904/
