### ISSUE TITLE
[Problem-Bug] User not in friendly team but apears in match chat

### ISSUE THREAD

**Issue by vasilegherasim** [IroncladGames/SinsOfADarkAge#905]
A  user, apparently not in the friendly team can chat in a pre-match lobby.
![user](https://cloud.githubusercontent.com/assets/10153234/6178828/79fe3e62-b31b-11e4-90ac-40fc1d950801.jpg)

**Comment by uncannymanny** [comment]
Oh wow! Similar to this https://github.com/IroncladGames/SinsOfADarkAge/issues/233 in theory, but this new one can be bad!

**Comment by vasilegherasim** [comment]
Well, that player wasn't even on the enemy team.

**Comment by uncannymanny** [comment]
My first theory was maybe he changed his name, but that may not have been the case.

Pretty peculiar issue. Good eye!

Might need the log file from that session: http://soada.wikia.com/wiki/Finding_a_Log_File (About 15 hours ago.)

**Comment by vasilegherasim** [comment]
Log file attached. Rename to .txt
![log-feb12_23_10_10](https://cloud.githubusercontent.com/assets/10153234/6192203/4ccf1a4a-b3b8-11e4-9732-a3c0a7d1e46b.png)

**Comment by uncannymanny** [comment]
Thank you for the upload!

**Comment by jseward** [comment]
Fixed as of 42744

**Comment by vasilegherasim** [comment]
Hmm, i didn't get that update, i'm still on 42616

**Comment by writor** [comment]
That's an internal dev update, the fix should be included in the next patch. Thanks vas!
