### ISSUE TITLE
Stolen moments

### ISSUE THREAD

**Issue by Oblivionn** [IroncladGames/SinsOfADarkAge#907]
The last two lines of the last page go off the bottom of the book.
Could happen with other lore books, don't have any others to test.

**Comment by writor** [comment]
Ah, this probably happened when we changed the font...I'll investigate further to see what can be done.

Thanks!

**Comment by writor** [comment]
The spacing issue should be fixed in the next patch (and is already fixed as of internal build 42796). Thanks Oblivionn!
