### ISSUE TITLE
Custom game autofilled with golems

### ISSUE THREAD

**Issue by writor** [IroncladGames/SinsOfADarkAge#908]
When creating a custom game in the Dev Build, the North team is automatically filled with golems.

![screenshot-000](https://cloud.githubusercontent.com/assets/6934405/6190739/eefe906c-b358-11e4-8713-703f6e8bd56d.jpg)

**Comment by uncannymanny** [comment]
Cool. Hopefully is a time saver? Or a bug.

Interesting, it's sort of related to this:https://github.com/IroncladGames/SinsOfADarkAge/issues/547#issuecomment-45712438

**Comment by writor** [comment]
I think it's a bug (if it's a time saver, no one was willing to tell me). :P

**Comment by writor** [comment]
Fixed as of February 20th internal builds.
