### ISSUE TITLE
Bug with the Gryphon.

### ISSUE THREAD

**Issue by elvensmile** [IroncladGames/SinsOfADarkAge#911]
It didnt do nothing but die.

Highlight:
http://www.twitch.tv/elvensmile/c/6116099

Game ID: 181713

**Comment by uncannymanny** [comment]
Bad Lucy/Grisha. Bad!

Go back to your Gryphon Pen!

Thanks for the report, Eruven!

**Comment by fyst** [comment]
Fixed as of 42958
