### ISSUE TITLE
Options Text Color Issue

### ISSUE THREAD

**Issue by uncannymanny** [IroncladGames/SinsOfADarkAge#914]
This is a composite image, but if you select each button in Options, some have white text and some have yellow text.

![2015-02-18_00001](https://cloud.githubusercontent.com/assets/6155683/6249121/0945dc66-b753-11e4-96f8-0e44d2143e49.jpg)

Graphics, Gameplay, Keybindings, HUD are all white when selected.

Sound, Ico, Voice Chat, and Language are all yellow when selected.

**Comment by jseward** [comment]
Fixed as of 42826
