### ISSUE TITLE
game does not run , when i click the play button then it is goes to update but it's say connection time out 

### ISSUE THREAD

**Issue by uddin9live** [IroncladGames/SinsOfADarkAge#919]

**Comment by uddin9live** [comment]
![untitled](https://cloud.githubusercontent.com/assets/10755727/6281005/be9401ee-b8e1-11e4-8e07-0c546984dab6.png)

**Comment by uddin9live** [comment]
![untitled](https://cloud.githubusercontent.com/assets/10755727/6281036/2d93d8c6-b8e2-11e4-861f-bcedc35b2043.png)

**Comment by uddin9live** [comment]
anyway im downloading again on a  new pc , i will let u know

**Comment by uncannymanny** [comment]
Thanks for the update.

One thing you can do is:

right click on Sins of a Dark Age in your game Library.

Click Properties.

Go to Local Files tab.

Verify Integrity of Game Cache.

See if that fixes it.

If not right click on Sins of a Dark Age in your game Library.

Click Properties.

Go to Local Files tab.

Delete Local Content.

Go to Windows Uninstall or Change a Program and uninstall Soada there.

Then reinstall and see how goes.

**Comment by uddin9live** [comment]
It is updating now ...  about 295 mb


Thank you

**Comment by uncannymanny** [comment]
Awesome.

As always, if any issues or questions, you know where to find me!

**Comment by uncannymanny** [comment]
Confirmed in-game closing.
