### ISSUE TITLE
Enemy Lassidar Static Field No Orange Dot Outline

### ISSUE THREAD

**Issue by uncannymanny** [IroncladGames/SinsOfADarkAge#924]
Should an enemy Lassidar's Static Field show the red/orange dot outline?

![2014-01-24_00001](https://f.cloud.github.com/assets/6155683/1997263/1f8192e0-8522-11e3-8966-9c7f537b3f92.jpg)

![2015-02-23_00001](https://cloud.githubusercontent.com/assets/6155683/6323276/5ee09f44-baf5-11e4-9dad-8bea8bb6bd2a.jpg)

**Comment by fyst** [comment]
Fixed as of 42993.
