### ISSUE TITLE
Critter Meat

### ISSUE THREAD

**Issue by CrackerJax** [IroncladGames/SinsOfADarkAge#928]
Unable to retrieve Critter Meat when enemy was killed while delivering it to his Gryphon. Was able to select but not retrieve when tried from various angles.

![2015-02-23_00002](https://cloud.githubusercontent.com/assets/7759801/6333219/eabbe810-bb50-11e4-9b47-80c576ffb1cb.jpg)

**Comment by uncannymanny** [comment]
Gameid 206443

**Comment by uncannymanny** [comment]
I remember something like this sort of happened against the Hydra.

Approximate location of pelts in my case (in which the hero couldn't make his mind between attacking the hydra can getting the pelts):

![hydra_cam](https://cloud.githubusercontent.com/assets/6155683/6335123/3beef82e-bb67-11e4-8376-92c1fe5981ee.png)

Maybe it was an attack move thing. Not sure I just remember that area giving me trouble when someone died there, and I couldn't pick up their pelts.

**Comment by CrackerJax** [comment]
Yes, I remember that too, manny. Also I remember it being stuck under an altar once before.

**Comment by fyst** [comment]
Fixed as of 43733
