### ISSUE TITLE
Enemy Ability Outline Issues

### ISSUE THREAD

**Issue by uncannymanny** [IroncladGames/SinsOfADarkAge#94]
Found a weird misplaced outline for an enemy Slag's Tar Ball:

![2013-12-15_00001](https://f.cloud.github.com/assets/6155683/1750003/3b641f46-6560-11e3-91b1-736c2efe9846.jpg)

See how the orange outline is next to the actual Tar Ball slick?

Here is another:

![2013-12-16_00001](https://f.cloud.github.com/assets/6155683/1753602/ea34ef3e-663f-11e3-960e-63de00e4220c.jpg)

See Skalla's trap? It has a double orange dotted outline.

Now look what happens when I zoom in:

![2013-12-16_00004](https://f.cloud.github.com/assets/6155683/1753609/fd8b7fda-663f-11e3-9216-fa409378f9ff.jpg)

Zooming out returns to the double outline again.

Here is an enemy Slag's Tar Ball:

Up close:
![2013-12-16_00021](https://f.cloud.github.com/assets/6155683/1755251/b5d211f0-6661-11e3-8a43-3de8519c3d69.jpg)

Far away:
![2013-12-16_00020](https://f.cloud.github.com/assets/6155683/1755258/cd8b1418-6661-11e3-8327-91c1356623da.jpg)

Notice how the orange outline disappears.

Tar Balls are easy to spot, I will have to see how Skalla's traps are affected since they can be hard to see when not paying attention/in the jungle.

**Comment by fyst** [comment]
Fixed as of 42935. Please pull the lassidar issue into its own bug. Seperete issue.
