### ISSUE TITLE
[Problem - BUG] Low framerate in Try Hero mode

### ISSUE THREAD

**Issue by vasilegherasim** [IroncladGames/SinsOfADarkAge#948]
When playing in try hero mode, the framerate drops at about 10fps when dealing large horde of minions.

**Comment by uncannymanny** [comment]
Is this drop in performance new?

Did it happen in the past or is it a recent issue?

Try lowering all your graphics settings to low or off to see if that solves the issue.

Then try playing with Exclusive and Windowed mode.

Play with each setting to see if there is one particular one causing the issues.

If the same issue happens with everything on Low (and if resolution options have no effect), you can then try to send a bug report in game by pressing escape which will send a copy of your log file for the devs to look over.

**Comment by vasilegherasim** [comment]
Resolved, with vga driver update.

**Comment by uncannymanny** [comment]
Thanks for the update!
