### ISSUE TITLE
Scrimmage Defeat

### ISSUE THREAD

**Issue by CrackerJax** [IroncladGames/SinsOfADarkAge#958]
2v2 Scrimmage shows as defeat when players leave for a 5v5.
![2015-03-21_00001](https://cloud.githubusercontent.com/assets/7759801/6766585/e71afd84-cfd9-11e4-8059-834da4fb58d5.jpg)

**Comment by Oblivionn** [comment]
Should still show up in history if someone stays and finishes the game.
if everyone leaves the game is disbanded.

**Comment by CrackerJax** [comment]
All four of us left for a 5v5 and we all received defeat status. :'(

**Comment by Oblivionn** [comment]
The game in question, id-292470, torrace didn't leave and won the game through destroying the tower, he had 38 cs, 2k gold earnt, and the game was 5 minutes and 12 seconds long.

**Comment by CrackerJax** [comment]
AH poo. I thought he was in the match with us. My bad. Delete if you wish

**Comment by uncannymanny** [comment]
Thanks for looking into it.
