### ISSUE TITLE
BugID 123?  Game version mismatch but no new game version to DL

### ISSUE THREAD

**Issue by Icypolefreak** [IroncladGames/SinsOfADarkAge#960]
As title states, nothing more, haved tried reloading steam, verifying game cache. I have yet to try un-intalling and re-installing SOADA

**Comment by uncannymanny** [comment]
I believe Soada's live servers went down temporarily.

Are you able to log in now? (2:31 pm EST)

**Comment by Icypolefreak** [comment]
I am now able to log in, cheers.

**Comment by uncannymanny** [comment]
Thanks for the reports.

A new patch just hit, so if you have any issues, you may have to Exit Steam and reboot it to force the download.

If any issues or questions, you know where to find me!
