### ISSUE TITLE
[Problem - BUG] Back Towers on Try Hero can't be destroyed

### ISSUE THREAD

**Issue by vasilegherasim** [IroncladGames/SinsOfADarkAge#961]
As of the latest update.
The back towers in Try Hero mode can't be destroyed anymore after you destroy the front tower.

**Comment by Oblivionn** [comment]
"Fixed a bug where some of the back towers in the Duel map were vulnerable to attack."

**Comment by uncannymanny** [comment]
It is my understanding that they were never intended to be destroyed in the first place, as this led to the eventual issue where your minions would clog up the spawn point of the enemy minions.

**Comment by uncannymanny** [comment]
Thanks for the report though! Closing as the towers are now working as intended.
