### ISSUE TITLE
Founder Vexie Not Appearing in Inventory

### ISSUE THREAD

**Issue by Ekko-Tek** [IroncladGames/SinsOfADarkAge#970]
I checked transactions after the latest patch and inventory, but no Vexie. Here is a screenshot:
http://steamcommunity.com/sharedfiles/filedetails/?id=422651780
I noticed Exorcised had reported the same problem as well on Steam forums.

**Comment by uncannymanny** [comment]
Thanks for the post. I guess my theory of it generating upon login was incorrect.

I have forwarded this to the devs.

**Comment by jseward** [comment]
should be there now! sorry my bad.

**Comment by Ekko-Tek** [comment]
It's there now, thank you. However, the portrait for it is Luna Moth Vexie.

**Comment by uncannymanny** [comment]
Ah yes. Some of the art assets aren't loaded yet such as its hero pedestal or its store art asset.

Same with the Twitter Loyalty Chest.

The art will come in time!

(Whether a temporary or the actual splash art comes first I do not know.)
