### ISSUE TITLE
Bug with HUD [Interface]

### ISSUE THREAD

**Issue by makssof** [IroncladGames/SinsOfADarkAge#972]
Just watch screen:
http://steamcommunity.com/sharedfiles/filedetails/?id=433329272

**Comment by makssof** [comment]
After watcing replays, and click on "Hide HUD" (Or?..) button
sry for very bad eng.

**Comment by Tugimus** [comment]
You can press Alt-C to bring back the HUD :)

It should not carry that status over from Replay to in game, though, so thankyou for finding it!

**Comment by makssof** [comment]
aww, thx, and sry :)

**Comment by makssof** [comment]
Aww, thx and sry :)
