### ISSUE TITLE
#SOADA PATCH

### ISSUE THREAD

**Issue by jhajay** [IroncladGames/SinsOfADarkAge#974]
Hello! how long is the SOADA will patch? Is that the last patch? How many updates or patch you will have today? Thanks!

**Comment by uncannymanny** [comment]
I do not know how many more patches are planned.

The most recent one was a 12mb patch.

It seems as of 20 minutes ago, the servers and patch are caught up.

If you have any further issues later today, feel free to post them here or on the forums: http://steamcommunity.com/app/251970/discussions/

**Comment by jhajay** [comment]
Okay. Thanks for your response. :) I appreciate it.
