### ISSUE TITLE
In-Game UI Sounds vs. Hot Key Sounds

### ISSUE THREAD

**Issue by uncannymanny** [IroncladGames/SinsOfADarkAge#99]
If you click the buttons on the UI "Open Item Shop" and "Open Glyph Shop," these buttons make a noise when entering either shop. (They are below your inventory.)

However, if you use O or P to get to these two shops, there is no sound. (Sounds like a door opening)

If you click on the stats in the bottom left of your screen (right next to your character art work,) there is a sound for the in-game hero comparison tool; however, there is no sound for when you press C. (Sounds like a menu click.)

![2013-12-16_00025](https://f.cloud.github.com/assets/6155683/1755631/a1ff7da6-6667-11e3-89f8-85e863fe556a.jpg)

Similarly with Menu and F10/Escape.

**Comment by braffles** [comment]
Hotkey sounds are not intended.
