### ISSUE TITLE
Top Rated Replays(Player Names)

### ISSUE THREAD

**Issue by FragumZ** [IroncladGames/SinsOfADarkAge#997]
I noticed players name are not matching correctly. The arrows within the image will show in the example: ![Possible Bug?](http://i.imgur.com/w9LMuDK.png)

- FragumZ

**Comment by uncannymanny** [comment]
My understanding is that the blue and purple game summary screen shows the name of that player during that game session. (I suppose Mitch goes back and forth between the two).

The Game Replay area might be more up to date with the user's current Steam Handle.

Will have to verify though.

**Comment by FragumZ** [comment]
I actually have confirmed this just now, both mitches are the same, he had just changed his steam name, thats all. You can go ahead close this report :) Thank you.
